# This workflow will do a clean install of node dependencies, build the source code, and deploy the updated site to github pages.

name: Deploy to GH Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Use NodeJS 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - run: yarn install && yarn deploy
